/*    ==Parametri di scripting==

    Versione server di origine : SQL Server 2016 (13.0.4224)
    Edizione motore di database di origine : Microsoft SQL Server Standard Edition
    Tipo motore di database di origine : Istanza di SQL Server autonoma

    Versione server di destinazione : SQL Server 2016
    Edizione motore di database di destinazione : Microsoft SQL Server Standard Edition
    Tipo motore di database di destinazione : Istanza di SQL Server autonoma
*/

USE [master]
GO

/****** Object:  Database [Progetto Medico ]    Script Date: 12/04/2019 13:31:17 ******/
CREATE DATABASE [Progetto Medico ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Progetto Medico', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Progetto Medico .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Progetto Medico _log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Progetto Medico _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Progetto Medico ] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Progetto Medico ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Progetto Medico ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Progetto Medico ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Progetto Medico ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Progetto Medico ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Progetto Medico ] SET ARITHABORT OFF 
GO

ALTER DATABASE [Progetto Medico ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Progetto Medico ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Progetto Medico ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Progetto Medico ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Progetto Medico ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Progetto Medico ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Progetto Medico ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Progetto Medico ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Progetto Medico ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Progetto Medico ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Progetto Medico ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Progetto Medico ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Progetto Medico ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Progetto Medico ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Progetto Medico ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Progetto Medico ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Progetto Medico ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Progetto Medico ] SET RECOVERY FULL 
GO

ALTER DATABASE [Progetto Medico ] SET  MULTI_USER 
GO

ALTER DATABASE [Progetto Medico ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Progetto Medico ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Progetto Medico ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Progetto Medico ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Progetto Medico ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Progetto Medico ] SET QUERY_STORE = OFF
GO

USE [Progetto Medico ]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Progetto Medico ] SET  READ_WRITE 
GO


 